---
- name: Playbook without Vault
  hosts: localhost
  tasks:
    - name: include vault
      ansible.builtin.include_vars:
        file: mypassword.yml
        
    - name: print variable
      ansible.builtin.debug:
        var: devsshpass