---
- name: find demo
  hosts: all
  vars:
    mypath: "/home/devops/example"
  tasks:
    - name: search files
      ansible.builtin.find:
        paths: "{{ mypath }}"
        hidden: true
        recurse: true
        file_type: any
        patterns: '*.cnf'
      register: found_files

    - name: print files
      ansible.builtin.debug:
        var: found_files
